version: "3.9"

services:
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    env_file:
      - .env
    restart: always
    container_name: admin
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    env_file:
      - .env
    restart: always
    container_name: frontend
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: always
    depends_on:
      - admin
      - frontend
    ports:
      - "3000:80"
    container_name: nginx
    networks:
      - mynetwork

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/backend/Dockerfile
  #   restart: always
  #   container_name: backend
  #   networks:
  #     - mynetwork
networks:
  mynetwork:
