version: "3.9"

services:
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    image: admin-dev
    restart: always
    container_name: admin-dev
    volumes:
      - ./apps/admin/src:/usr/src/app/apps/admin/src:ro
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    image: frontend-dev
    restart: always
    container_name: frontend-dev
    volumes:
      - ./apps/frontend/src:/usr/src/app/apps/frontend/src:ro
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    image: backend-dev
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    container_name: backend-dev
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src:ro
    networks:
      - mynetwork

  db:
    image: postgres
    env_file:
      - .env
    container_name: db-dev
    restart: always
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.dev
    image: nginx-dev
    restart: always
    depends_on:
      - admin
      - frontend
      - backend
    ports:
      - 3000:80
      - 443:443
    container_name: nginx-dev
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    links:
      - db:db
    networks:
      - mynetwork

networks:
  mynetwork:
