version: "3.9"

services:
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    env_file:
      - .env
    restart: always
    container_name: admin
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    env_file:
      - .env
    restart: always
    container_name: frontend
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    container_name: backend
    networks:
      - mynetwork

  db:
    image: postgres
    env_file:
      - .env
    container_name: db
    restart: always
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: always
    depends_on:
      - admin
      - frontend
      - backend
    ports:
      - "3000:80"
    container_name: nginx
    networks:
      - mynetwork

networks:
  mynetwork:
