version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:8000"
    restart: always
    container_name: app
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    container_name: database-docker
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
