version: "3.9"

services:
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    container_name: admin
    networks:
      - mynetwork
networks:
  mynetwork:
